# frozen_string_literal: true

require "find"
require "json"
require "thread"

require "ask-coding-providers"

module Ask
  module CodingHarness
    # A scripted coding agent for trying the harness without API keys.
    #
    # Walks through a realistic turn — todos, tool calls with output, a
    # diff, and a tool call queued for human approval — waiting on the
    # approval queue exactly like the real ask_agent adapter. The text and
    # file contents are generated from the workspace it is pointed at, so
    # every run feels like the real thing.
    #
    #   ach demo            # serve the web UI against the demo agent
    class DemoAdapter < Ask::CodingProviders::Adapter
      def initialize(**)
        @pending = {}
        @next_action_id = 1
        @mutex = Mutex.new
        @cv = ConditionVariable.new
        @aborted = false
        @sessions = {}
      end

      def start; end
      def stop
        @mutex.synchronize { @aborted = true; @cv.broadcast }
      end

      def create_session(workspace_path, mode: nil, model: nil)
        sid = "demo_#{@sessions.size + 1}"
        @sessions[sid] = workspace_path
        sid
      end

      def send_and_stream(session_id, content, turn_timeout: 600.0, &block)
        workspace = @sessions[session_id] || Dir.pwd
        emit(block, "turn.started", {})

        emit(block, "model.streaming", { "delta" => "Alright, let me take a look at #{File.basename(workspace)}. " })
        emit(block, "model.streaming", { "delta" => "I'll start by mapping the project structure.\n\n" })

        emit(block, "todos.updated", {
          "todos" => [
            { "id" => "1", "title" => "Inspect the project structure", "status" => "in_progress" },
            { "id" => "2", "title" => "Find the main entry point", "status" => "pending" },
            { "id" => "3", "title" => "Propose improvements", "status" => "pending" }
          ]
        })

        files = list_files(workspace)
        emit(block, "tool.use", {
          "toolName" => "bash", "toolCallId" => "call_1",
          "input" => { "command" => "find . -type f | head -30" }
        })
        emit(block, "tool.result", {
          "toolName" => "bash", "toolCallId" => "call_1",
          "output" => files.join("\n"),
          "isError" => false, "durationMs" => 84
        })

        readme = read_first(workspace, %w[README.md readme.md])
        if readme
          emit(block, "tool.use", {
            "toolName" => "read", "toolCallId" => "call_2",
            "input" => { "path" => readme[0] }
          })
          emit(block, "tool.result", {
            "toolName" => "read", "toolCallId" => "call_2",
            "output" => readme[1],
            "isError" => false, "durationMs" => 12
          })
        end

        emit(block, "todos.updated", {
          "todos" => [
            { "id" => "1", "title" => "Inspect the project structure", "status" => "completed" },
            { "id" => "2", "title" => "Find the main entry point", "status" => "completed" },
            { "id" => "3", "title" => "Propose improvements", "status" => "in_progress" }
          ]
        })

        emit(block, "model.streaming", {
          "delta" => "I can see the project has #{files.size} files. Here's a diff I'd like to apply — it needs your approval first:\n\n"
        })

        emit(block, "tool.use", {
          "toolName" => "apply_patch", "toolCallId" => "call_3",
          "input" => { "patch" => "diff --git a/README.md b/README.md\nindex 8f1a2b3..c9d4e5f 100644\n--- a/README.md\n+++ b/README.md\n@@ -1,3 +1,4 @@\n # #{File.basename(workspace)}\n \n+Generated by the ask-coding-harness demo agent.\n" }
        })

        # Queue an approval — the demo pauses here until the user decides.
        action_id = queue_action(block, "apply_patch", { "patch" => "…" }, "Applying a patch to README.md requires approval")
        outcome = wait_for_decision(action_id)

        case outcome
        when :approved
          emit(block, "approval.updated", { "actionId" => action_id, "status" => "approved" })
          emit(block, "tool.result", {
            "toolName" => "apply_patch", "toolCallId" => "call_3",
            "output" => "Patch applied to README.md",
            "isError" => false, "durationMs" => 5
          })
          emit(block, "model.streaming", {
            "delta" => "Done — README.md now documents that this workspace was demoed by the harness. " \
                      "Try asking me to do something real: point the harness at a project, add an API key, " \
                      "and I'll work through it with tools, approvals, and diffs just like this.\n\n" \
                      "Things to try: run tests, refactor a file, explain an error.\n"
          })
          emit(block, "turn.completed", { "response" => "Demo turn completed." })
        when :rejected
          emit(block, "approval.updated", { "actionId" => action_id, "status" => "rejected" })
          emit(block, "model.streaming", {
            "delta" => "Understood — I won't touch anything. That's the approval flow working: " \
                      "nothing mutates without your say-so.\n"
          })
          emit(block, "turn.completed", { "response" => "Demo turn completed (rejected)." })
        when :aborted
          emit(block, "turn.aborted", {})
        end
      end

      # ── Approval controls (same duck-typed surface as ask_agent) ──

      def approve_action(_session_id, action_id)
        @mutex.synchronize do
          action = @pending[action_id]
          next [] unless action
          @pending[action_id] = action.merge("status" => "approved")
          @cv.broadcast
        end
      end

      def reject_action(_session_id, action_id)
        @mutex.synchronize do
          action = @pending[action_id]
          next [] unless action
          @pending[action_id] = action.merge("status" => "rejected")
          @cv.broadcast
        end
      end

      def approve_all(_session_id)
        @mutex.synchronize do
          @pending.each_value { |a| a["status"] = "approved" if a["status"] == "pending" }
          @cv.broadcast
        end
      end

      def pending_approvals(_session_id)
        @mutex.synchronize do
          @pending.values.select { |a| a["status"] == "pending" }
        end
      end

      def abort(_session_id)
        @mutex.synchronize { @aborted = true; @cv.broadcast }
      end

      # ── Registration ──

      def self.install!
        existing = begin
          Ask::CodingProviders.resolve_adapter(:demo)
        rescue Ask::CodingProviders::ConfigurationError
          nil
        end
        Ask::CodingProviders.register_adapter(:demo, self) unless existing
      end

      private

      def emit(block, type, payload)
        block.call({ type: type, seq: 0, payload: payload })
      end

      def queue_action(block, tool_name, args, message)
        @mutex.synchronize do
          id = @next_action_id
          @next_action_id += 1
          @pending[id] = {
            "id" => id, "tool_name" => tool_name, "args" => args,
            "message" => message, "status" => "pending"
          }
          emit(block, "approval.required", {
            "actionId" => id, "toolName" => tool_name, "args" => args,
            "message" => message, "autoApprovable" => false, "status" => "pending"
          })
          id
        end
      end

      # Block until the action is approved, rejected, or the turn aborts.
      def wait_for_decision(action_id)
        @mutex.synchronize do
          loop do
            return :aborted if @aborted
            action = @pending[action_id]
            return action["status"].to_sym if action && action["status"] != "pending"
            @cv.wait(@mutex, 0.5)
          end
        end
      end

      def list_files(workspace)
        ignore = %w[.git node_modules vendor tmp log coverage data]
        files = []
        Find.find(workspace) do |path|
          rel = path.sub("#{workspace}/", "")
          next if rel.empty?
          parts = rel.split("/")
          next if parts.any? { |p| ignore.include?(p) || p.start_with?(".") }
          next unless File.file?(path)
          files << rel
        end
        files.sort.first(30)
      end

      def read_first(workspace, names)
        names.each do |name|
          path = File.join(workspace, name)
          next unless File.file?(path)
          content = File.read(path, encoding: "UTF-8")
          return [name, content.lines.first(40).join]
        end
        nil
      end
    end
  end
end

Ask::CodingHarness::DemoAdapter.install!
